### ISSUE TITLE
Is there a way to add a new dimension to base_unit ?

### ISSUE THREAD

**Issue by tarberd** [nholthaus/units#103]
I'm having a little of a problem. For some reason I want to have two diferent length units types, micrometers and database_units and I can only have the ratio betwen them at runtime by reading some files. I would like to have a compilation error whenever I try to implicit convert betwen them. To solve that I was probably going to define database_units as some weird new dimention to and handle the conversion elsewhere. Any Ideas ??

**Comment by nholthaus** [comment]
I'm planning to support user-defined and arbitrary dimensions in 1.3 by incorporating https://github.com/swatanabe/cppnow17-units. Don't really have a timeline (short of someone contracting me for it in the meantime) but it's the next thing I'm planning to do to the library.

So your current choices, are:
1. wait for that
2. Expand the `base_unit` struct similar to what was done for byte/radian
3. replace the `base_unit` struct with something like the link above.

Unfortunately all the pre-1.3 options require getting your hands dirty.
