### ISSUE TITLE
Missing operations to match a std:: quantity

### ISSUE THREAD

**Issue by johelegp** [nholthaus/units#105]
Greetings.

I had attempted to match `units::length::meter_t` against a concept that checks that a type matches the `std::chrono::duration` interface of a quantity without dimensional analysis capabilities. This led me to find out that the library quantity types are missing the unary plus and pre and post increment and decrement operators.

I didn't find any reason for their lack, so I'd like to suggest their addition for the benefit of interface consistency (specially in generic interfaces) and convenience (we prefer ++x to x+=1, don't we?)

Thanks for reading.

**Comment by nholthaus** [comment]
thanks, probably just an oversight. Should be in the next minor release.

**Comment by nholthaus** [comment]
also, if you don't mind sharing your concept check, I could add it to the unit testing.

**Comment by johelegp** [comment]
I used [these concepts](https://github.com/johelegp/Made_in_Abyss/blob/devel/include/mia/concepts.hpp). With a [proper extension](https://github.com/johelegp/Made_in_Abyss/blob/devel/include/mia/ext/units.hpp) to support the `std::chrono::duration`-like `common_type` semantics and with the changes that closed this issue, the types of this library pass the [tests](https://github.com/johelegp/Made_in_Abyss/blob/devel/test/concepts.cpp).

**Comment by nholthaus** [comment]
Thank you for sharing! You should have the operators you need in 2.3.1, and I'm going to add common_type support to 3.0 because of this. 

Your code looks really good. If you come up with anything you think belongs in the mainline, don't hesitate to make a PR!

**Comment by johelegp** [comment]
Thanks to you too!
