### ISSUE TITLE
Add support for complex numbers

### ISSUE THREAD

**Issue by nholthaus** [nholthaus/units#11]

**Comment by nholthaus** [comment]
Boost::units (possibly other libraries?) have the capability to handle complex unit values. I think `units` probably can too either by changing the `UNIT_LIB_DEFAULT_TYPE`, or be creating a `unit_t<someUnit, std::complex>` type. 

That said, I'm not really that familiar with using complex types in c++ and I'm not sure I have the use case/motivation to work on it in the near term.

If this is interesting to anyone, feel free to let me know!

**Comment by EvanBalster** [comment]
Is there any reason std::complex<someUnit> wouldn't work?

This brings up the interesting question of which type heirarchy is correct:
1. `vec3<complex<meters<float>>>>`
2. `vec3<meters<complex<float>>>>`
3. `meters<vec3<complex<float>>>>`

The main issue I see with (1.) is that the domain isn't defined in a compact way, with the dimensionality sitting in the middle.  I'm not sure if this constitutes a problematic practical burden, though.

**Comment by nholthaus** [comment]
My intuition is 2 is the most proper.

I'm less worried about the typedef itself than I am about all the math and functions working correctly, but since I personally don't have a use case for it (aside from shutting down the last argument to use boost::units instead) I wasn't planning on putting the time into testing it. It may just work.

**Comment by Morwenn** [comment]
While it would probably work most of the time, 1. is unspecified behaviour according to [complex.numbers]/2 in the standard:

> The effect of instantiating the template complex for any type other than `float`, `double`, or `long double` is unspecified.

I agree that 2. looks like the best solution to handle the problem.

**Comment by nholthaus** [comment]
My plan for `v2.3.0` is going to be to add some unit tests using the '2' style. If it works, great, I'll document it. If not (e.g. if another cmath wrapper function set is needed, or the arithmetic operators don't support it), I'll probably close the issue.

**Comment by nholthaus** [comment]
Results of the testing were not very good.

`std::complex<double>` is not a trivial type, so supporting it would break existing library guarantees. 

In addition, the return type deduction of just about every member and non-member function would need to be re-written to determine whether the resulting type should be complex or not, and there would need to be support added for fixed complex/non-complex arithmetic. A fringe benefit of this would be better support for mixed integral/floating point underlying unit types.

It would probably be possible to do, but I think the use case is marginal (maybe some electrical engineering applications), and I'm not sufficiently interested in the problem at present to want to tackle such a big job.
