### ISSUE TITLE
Diferring dimensionless comparison semantics

### ISSUE THREAD

**Issue by johelegp** [nholthaus/units#130]
Comparing a `dimensionless` with an arithmetic type uses [`std::isgreaterthan` and `std::islessthan`](https://github.com/nholthaus/units/blob/57324b8d5d5590943a27e5da546f964401754f9a/include/units.h#L2594) for `operator>=` and `operator<=`, while comparing two `dimensionless` use the built-in [`operator>=` and `operator<=`](https://github.com/nholthaus/units/blob/57324b8d5d5590943a27e5da546f964401754f9a/include/units.h#L1927). That's surprising. I'd expect `dimensionless(1) <= 1` to behave exactly as `dimensionless(1) <= dimensionless(1)`.

**Comment by nholthaus** [comment]
yes. They should probably all use the built-in operators.
