### ISSUE TITLE
Improve genericity by removing the namespace `math`.

### ISSUE THREAD

**Issue by le-migou** [nholthaus/units#145]
Let's say I'm building the following  generic library
```cpp
    template <class T> void
f (T x)
{
    sqrt (x);
}
```
. Using it with units won't work because the `sqrt` function is in the namespace `math` and ADL will not find it. 
```cpp
int main ()
{
    using namespace units::literals;
    f (1);
    f (1_K); // <- Error: no matching call to sqrt.
}
```
. Putting all the math overloaded functions in the namespace of `unit_t` is the way to go in order for ADL to work. (See recommendations [C.5](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#c5-place-helper-functions-in-the-same-namespace-as-the-class-they-support) and [C.168](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#c168-define-overloaded-operators-in-the-namespace-of-their-operands) of the Core Guidelines.) So I propose to remove the namespace `math` entirely.

**Comment by nholthaus** [comment]
100% right. This has already been corrected in the v3.x development. No plans to change namespacing in the 2.x line.

You may want to try out [v3 alpha 2](https://github.com/nholthaus/units/releases/tag/v3.0.0.alpha-2). It's more stable than the name implies and has a lot of improvements for generality and sfinae friendliness, although we still have a way to go.
