### ISSUE TITLE
New Unit: mmhg

### ISSUE THREAD

**Issue by nanowizard** [nholthaus/units#147]
First off, this library is awesome! Thank you for making this available.

I would like to see mmhg (millimeters of mercury) for units of pressure, which is ["precisely 133.322387415 pascals"](https://en.wikipedia.org/wiki/Millimeter_of_mercury).

I believe this would be defined as follows in the `pressure` namespace:

`UNIT_ADD(pressure, mmhg, mmhg, mmHg, unit<std::ratio<26664477483LL, 200000000LL>, pascals>)`

Let me know if that looks incorrect though.

**Comment by johelegp** [comment]
>Let me know if that looks incorrect though.

The capitalization of the abbreviation (Wikipedia suggests mmHg) and using the `LL` suffix for the literals of the `std::ratio` which might overflow an `int`.

**Comment by nanowizard** [comment]
@johelegp Both excellent points, thank you. I've updated the request above with your suggested changes.

**Comment by nholthaus** [comment]
Adding it won't be a problem. That conversion factor is rough though, and this unit is going to overflow like crazy if you do anything very complicated with it. As a practical matter, it may be better to approximate `mmHg` with `Torr`.

**Comment by nanowizard** [comment]
@nholthaus that's a good point. Defined exactly in terms of `torrs` would make the ratio 42115229 : 42115223. A close approximation would be 6178355 : 6178354.

The difference between the two units is so small that I don't think we could effectively reduce the ratio values below that without making them 1 : 1.

**Comment by nholthaus** [comment]
added to the latest 3.x. I used the original (official) definition because as a design principle no approximations are used in the library.

**Comment by nanowizard** [comment]
I've noticed a couple of other unit definitions that use pretty large numbers which would easily overflow an `int`, such as `foot_pound` and `lightyears`. Should those be changed to use the `LL` suffix as well?
