### ISSUE TITLE
cannot convert coulomb/volt into farad

### ISSUE THREAD

**Issue by evenex** [nholthaus/units#148]
farad_t one_farad()
    { return coulomb_t(1) / volt_t(1); }

fails to compile with

    error: static assertion failed: Units are not compatible.

**Comment by nholthaus** [comment]
which version are you using?

**Comment by evenex** [comment]
Latest. sha1 of units.h is 40be29223786b357c23f8defea83fb516b5601dc

**Comment by evenex** [comment]
Unfortunately that version relies on inline variables and void_t, which aren't present in C++14 (I'm using gcc 5.4)

**Comment by johelegp** [comment]
On CE: https://godbolt.org/g/5QYUsZ (C++17, trunk), https://godbolt.org/g/yPEygd (C++14, master). Seems to be working fine.

**Comment by evenex** [comment]
https://godbolt.org/g/K6zRZE shows the error. Inline constexpr variables are in units.h but CE doesn't seem to hit the error on the included file for some reason.

**Comment by johelegp** [comment]
The v3.x branch and the v3 alpha releases require C++17.
