### ISSUE TITLE
int overflow problems?

### ISSUE THREAD

**Issue by nanowizard** [nholthaus/units#149]
When I suggested a [new unit for mmHg](https://github.com/nholthaus/units/issues/147), @johelegp suggested using the `LL` suffix to avoid `int` overflow. I have since noticed a couple of other units which are defined with pretty large ratios which would probably overflow an `int` such as `lightyear` and `foot_pound`. Should those be modified to use the `LL` suffix as well to avoid overflow problems?

**Comment by johelegp** [comment]
It seems like that was unnecessary. See "The type of the literal" at https://en.cppreference.com/w/cpp/language/integer_literal.

**Comment by nanowizard** [comment]
Indeed it looks like the suffix was unnecessary. The mmHg definition in 3.x should probably be changed then for consistency.
