### ISSUE TITLE
`typename` vs `class` for template parameters

### ISSUE THREAD

**Issue by johelegp** [nholthaus/units#166]
What's this library's convention for when to use one or the other? I find it hard to infer from the uses, as sometimes is seems contradicting from what I had previously inferred. I personally follow the standard's and only use `class`.

**Comment by nholthaus** [comment]
there is no convention. Since c++17 I think both keywords are allowed in _template template_ definitions so I don't think there's a functional difference between the two anymore.

**Comment by Morwenn** [comment]
Can confirm the lack of difference in C++17.

**Comment by johelegp** [comment]
Of course, the difference is only syntactical. I asked because some places use different keywords for the same parameter, and I wanted to be consistent.

**Comment by nholthaus** [comment]
understood. Pick whichever you prefer.
