### ISSUE TITLE
Basic functionality without any standard libraries.

### ISSUE THREAD

**Issue by zeel01** [nholthaus/units#188]
I'm attempting to create a unit conversion system running on an Arduino. This library, given how streamlined it is and its lack of dependencies, would almost be perfect to do the heavy lifting in that situation. However, this library still relies heavily on standard libraries... which of course Arduino doesn't have. 

What I'm wondering is, could a stripped down version of this (without, for example, cmath support) be possible by replacing things like std::ratio. Or is the dependance just too deep to even bother?

I'm not nearly well enough versed in templates to fully understand the inner workings here, so I apologize if this inquiry seems ridiculous.

**Comment by nholthaus** [comment]
definitely possible, but honestly not something that I'm going to do.
