### ISSUE TITLE
Equivalent units

### ISSUE THREAD

**Issue by gitsbi** [nholthaus/units#234]
I am currently checking out this unit library for inclusion in our next project. One problem I came across is that it seems impossible to create two units that are equivalent in their properties/dimensions, yet must not be mixed. For example, in electrical engineering there is, besides power (measured in `W`), also reactive power (`var`) and apparent power (`voltampere`). All are the result of multiplying voltage with current, but it is important that they are different units that the compiler sees as incompatible.

An in-house library I used to use supported that by their units having a `unique_tag` template parameter (which defaulted to `void`), and units with different tags being incompatible. 

Am I overlooking something (well possible) or does this (otherwise great!) library not currently offer such a feature?

**Comment by gitsbi** [comment]
Unfortunately, we need a unit test library soon, and it's questionable when we will have access to a compiler better than C++03 on one of our target platforms, and which version that will be. It definitely won't be C++20, though. I see more issues with this library, but those might not be show stoppers. But non-SI units that derive from SI units are an absolute must for us.

All this is a hassle to do in C++03 (BTDT), but it can be done comparatively easily in C++11. Yet, I have not found a library that has been around for a while and is actively maintained which has the mix of features we need and relies on nothing more that C++11. So it really looks like we need to do our own. 😞

**Comment by GElliott** [comment]
@gitsbi You might want to take a look at [boost's units library](https://www.boost.org/doc/libs/1_65_0/doc/html/boost_units.html) if you need C++03 support.  I have no doubt that you'll want to write your own wrappers---the API is pretty complex.  Last I checked, it also didn't support `constexpr` (possibly resolved by now).  That said, I've seen it used successfully in safety-critical commercial products.

What I like most about @nholthaus's library is (1) straightforward API and (2) `constexpr` support.

**Comment by gitsbi** [comment]
@nholthaus You might want to have a look at https://github.com/gitsbi/unlib to see what I have been cooking up since then.
