### ISSUE TITLE
Confirmed working on clang 3.7

### ISSUE THREAD

**Issue by twn346** [nholthaus/units#27]
This might be as expected, but I built it on clang-3.7.1 just for kicks. 

mkdir build
cd build
cmake ..
./unitTests/unitLibTest

all tests pass and was successfully compiled.

**Comment by twn346** [comment]
Not really an issue, but wasn't sure how else to contact you

**Comment by nholthaus** [comment]
Thanks for letting me know! We're you building on OSX by any chance?

**Comment by twn346** [comment]
I was not, I was actually on Gentoo. Do you need something built on OSX though?

**Comment by nholthaus** [comment]
It's a platform that I think `units` would work on, but I don't really have the means easily available to test it.

**Comment by twn346** [comment]
sure! just give me a bit and i'll add a comment when I know

**Comment by twn346** [comment]
Confirmed working with: 
Apple LLVM version 8.0.0 (clang-800.0.38)

on Mac OS sierra, to the extent that is passes all of the unit tests in ./unitTests/unitLibTest
