### ISSUE TITLE
A variable holding a unit initialized with the unary operator "-" cannot be constexpr

### ISSUE THREAD

**Issue by dsimonkay** [nholthaus/units#283]
`units` version: 2.3.1
Compiler version: g++ (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0

I want to define a variable holding a negative number with a unit. The variable needs to be `constexpr`, as it will appear in a `static_assert` later on.

The following code cannot be compiled:
```
#include "units.h"

int main()
{
    using units::literals::operator""_m;
    constexpr double whatever{-42.0_m};

    return 0;
}
```
The error:
```
units_bug.cpp:6:29: error: call to non-‘constexpr’ function ‘units::unit_t<Units, T, NonLinearScale> units::operator-(const units::unit_t<Units, T, NonLinearScale>&) [with Units = units::unit<std::ratio<1>, units::base_unit<std::ratio<1> > >; T = double; NonLinearScale = units::linear_scale]’
    6 |  constexpr double whatever{-42.0_m};
      |                             ^~~~~~
```

When adding `constexpr` to the definition of the unary operator:
![image](https://user-images.githubusercontent.com/11321246/149977368-435619df-4e58-435c-9300-c551660f0a1f.png)

The code can be compiled.

**Comment by JohelEGP** [comment]
That was added in https://github.com/nholthaus/units/commit/37a3175abf87e2922c799d4baf49513ba0c4212c.

**Comment by dsimonkay** [comment]
Ahh, thank you! I was led to [this specific link](https://github.com/nholthaus/units/releases/tag/v2.3.1) and missed to check the latest version.
