### ISSUE TITLE
Compound assignments?

### ISSUE THREAD

**Issue by EvanBalster** [nholthaus/units#44]
Is there any particular reason for the lack of compound assignment support in this library?  At a glance it looks like it would only be a few lines to implement the new operators (which I would be happy to contribute if necessary).

Currently I have many statements like this littering my code:
`joint.momentum = joint.momentum + dt * force;`

**Comment by nholthaus** [comment]
I'm not sure it can be done. I could be wrong though, and if so would welcome a patch.

There is some nuance to working with arithmetic operators in the units library. Not sure how deeply you've delved into the code, but `unit_t` types  are a CRTP construct inheriting from a so-called `non-linear scale`. The idea behind the NLS is that different arithmetic could be supported for different scales. So far, two are supported:

- linear scale: implements standard arithmetic
- decibel scale: implements log arithmetic for dB units

You could envision other logarithmic or exponential scales. I even did some testing that showed that datum-shifted scales like the Richter Scale were possible.

My recollection is a bit hazy, but I think when it came to compound assignment, I got foiled by the fact that base-class assignment isn't the same as inherited class assignment, or something like that. Or maybe it was just an oversight.

Additionally, you have to be careful with the `enable_if` template parameters (mostly not to break implicit conversion of dimensionless units back and forth to the underlying type), and the different RHS types that need to be supported. Copying an existing operator would be a good starting point.

**Comment by nholthaus** [comment]
note to self: maybe possible as [non-member](http://stackoverflow.com/questions/30278281/why-can-overloaded-compound-assignment-operators-be-non-member-functions)?

**Comment by nholthaus** [comment]
I take back what I said, I think this is an easy addition.

**Comment by EvanBalster** [comment]
Cool, thanks!  I had written my own implementation but I'll pull yours down now.

**Comment by nholthaus** [comment]
If you end up making any more improvements, feel free to share them back :)
