### ISSUE TITLE
Add data size units as first-class citizens

### ISSUE THREAD

**Issue by nholthaus** [nholthaus/units#46]
bit, byte, etc. Add a new `data` category to `struct base_unit`, as well as a `data_throughput` series of units.

**Comment by JaapAap** [comment]
As these are discrete units, would this allow them to be integer-based?

**Comment by nholthaus** [comment]
I don't think so, not in the general case.

Imagine you did:
`gigabyte_t size = 256_kB;`

You'd be expecting to get `0.000256`, not `0`. Or,

`gigabyte_t size_GB(1.2);`
`byte_t size_B = size;`

you'd be expecting `size == 1288490189;`

**Comment by nholthaus** [comment]
Right now there are basically two options for integral units:
1. Redefine the underlying type globally
2. Leave is as an exercise to the user to implement their own.

I'm starting to think that a third, more user-friendly option is needed, but I'm not sure what that should look like.

**Comment by JaapAap** [comment]
Understood. I currently use similar units that are rather defined in a similar way to how 'chrono' implements time units - I can then use them to e.g. set sizes of buffers (rather than involving them in arithmetic), which is a different use case I suppose.

**Comment by nholthaus** [comment]
It seems appropriate to implement this using the [ISO/IEC 80000](https://en.wikipedia.org/wiki/ISO/IEC_80000#Information_science_and_technology) standard. I.e.

`1_MB;`  - 1000<sup>2</sup> bytes
`1_MiB;` - 1024<sup>2</sup> bytes

Any qualms?

**Comment by JaapAap** [comment]
None whatsoever- like it.
