### ISSUE TITLE
Investigate header separation as a method to reduce compile-time.

### ISSUE THREAD

**Issue by nholthaus** [nholthaus/units#48]

**Comment by JaapAap** [comment]
Speaking on compilation times, I take it you have seen this? 
https://developercommunity.visualstudio.com/content/problem/10645/c-compiler-performance-issue-with-units-library.html?childToView=22624#comment-22624

**Comment by nholthaus** [comment]
yeah, those fixes are already in the 2.3.0 RC 2 and will be in the 2.3.0
release as well.

**Comment by nholthaus** [comment]
deprecated by the define/cmake options to opt-in to specific namespaces
