### ISSUE TITLE
Release v2.3.0

### ISSUE THREAD

**Issue by nholthaus** [nholthaus/units#62]
TODO:

- [ ] Document changes
- [ ] Release candidate feedback
- [ ] (maybe?) Remove `#defines` and appveyor references to VS2013. Refactor `typename std::... ::type` code that was reintroduced for VS2013.

RC 1 changes:

- #29 Add other definitions for year 
- #38 cout << 2.0_m * 2.0_m * 2.0_m * 2.0_m << endl;
- #44 Compound assignments
- #46 Add data size units as first-class citizens 
- #54 pascal defined elsewhere 
- #56 value() and value_type 

If interested, please try out the [release candidate](https://github.com/nholthaus/units/releases/tag/v2.3.0RC1). Feedback is welcome, including for additional features!

The goal is to provide a production release in early March.

**Comment by nholthaus** [comment]
RC2 changes:

 - Improved compile times
   - MSVC: 512%
   - GCC: 165%
 - Fixed constexpr relational operators bug (#63)

Retained VS2013 support.

**Comment by pvaibhav** [comment]
Something I did to help compile-time was to wrap all non-SI units in a disabled-by-default preprocessor #define. 99% of the time I don't need to deal with stones and furlongs and this improved my compilation time significantly on GCC-ARM.

Another suggestion I have is to split each category of units into its own header, e.g. one for voltages, current, impedance etc.; one for gravity-related etc.

I've not yet tried 2.3 RC2 (or 2.2 for that matter), but will do soon to see how much faster it can be now.

**Comment by nholthaus** [comment]
I have an investigation open to do exactly what you suggest in version 3. I'm trying to do a little work before hand to see _why_ the compile times scale with unit definitions (e.g. if there are more problems like the `operator<<` pollution), but assuming it's unavoidable I'll probably just end up splitting the definitions.
