### ISSUE TITLE
Question/feature request: Percentages

### ISSUE THREAD

**Issue by mlimber** [nholthaus/units#69]
Is there a way to handle percentages vis-à-vis decimal representation (5% vs. 0.05)? What would it take to implement that?

**Comment by nholthaus** [comment]
There is a percent unit currently in the library in the `concentration` namespace. You should be able to do something like:

```
#include <units.h>

using namespace units;
using namespace units::length;
using namespace units::concentration;
using namespace units::literals;

double result = 100 * 5_pct;
meter_t dist = 5_pct * 1_km;
```

If that's not working for you or not what you meant, let me know.

**Comment by mlimber** [comment]
Brilliant. Thanks!
