### ISSUE TITLE
Commit e26fcd7 causes VS 2017 compiler to crash

### ISSUE THREAD

**Issue by JaapAap** [nholthaus/units#70]
I get a fatal error C1001: An internal error has occurred in the compiler.
1>(compiler file 'msc1.cpp', line 1469)

A minimal example that causes this to occur:

void test(void)
{
	auto y1 = units::length::meter_t(1) * units::length::meter_t(1);
	auto y2 = units::length::meter_t(1) + units::length::meter_t(1); // VS 2017 chokes on this line
}

This might well be a VC++ issue - would anyone have a clue on what is going on here and how the latest commit would impact what happens under the hood?

**Comment by nholthaus** [comment]
Yeah that commit needs to be rolled back. I was trying to use some more of Microsoft's "hidden friend" technique to reduce the linux compile time, and I was able to shave about 40% off the build time, but then visual studio completely blew up.

The idea was: if I can move the `nls` operators into the class itself as hidden friends, I can reduce the amount of operator overload lookup, and simultaneously simplify the template `enable_if` checks, rendering them less expensive. It worked pretty well with gcc.

You may want to stick with v2.3.0 RC 2 for a while. The dev branch is going to be pretty experimental between now and RC 3, if there is one, while I attempt to reduce build time and see how badly I can break the compilers. RC 2 + some documentation updates may well end up being the final v2.3.0 release anyway.

**Comment by nholthaus** [comment]
This commit has been reverted.
