### ISSUE TITLE
minimal functionality and compilation speed

### ISSUE THREAD

**Issue by mlund** [nholthaus/units#77]
I'm testing `units.h` in a small project and get the following compile times using clang:

- ~1 sec before including `units.h`
- 11 secs after header inclusion
- 3 secs with `UNIT_LIB_DISABLE_IOSTREAM` macro

While all modest compilation times, it disturbs me to increase compilation time by an order of magnitude (I like to have `cout` functionality), especially since I use only a fraction of the defined units.  It would be great to have a way of including minimal functionality and add the needed units manually using the `UNIT_ADD` macro.

**Comment by mlund** [comment]
The above was done on the master branch and using 2.3.0RC2 the compilation time drops from 11 to 4 secs which is much better!

**Comment by nholthaus** [comment]
are you thinking a pre-processor define that would disable the built-in definitions?

**Comment by mlund** [comment]
Yes, that was my immediate thought in order to process just the core framework. Another option is to split into several headers (core, stream, length etc.), but I see the point of having just a single file.

**Comment by JaapAap** [comment]
Just wondering: for me, in fact, checking units is something that is really useful during development of the algorithmic parts of my code, but in fact something that I can do without once the algorithms all work 'as advertised'. It would really be nice not to have to pay for using the library at all (compile) times. To what extend would it potentially help to make the actual unit checking optional? Has this ever been considered at all?

**Comment by MikeGitb** [comment]
I'm not involved in the library, but afaik, you would have to make all units a alias for the respective built-in type, at which point you not only loose unit checking, but also things like overloading based on units.
In theory it could even hurt your runtime performance due to less effective alias analysis. Though I think, the latter is very unlikely.

**Comment by JaapAap** [comment]
Good point(s). Yes, I understand this is non-trivial as the conversion part would need to be retained as code would need to remain correct. Admittedly, it might not make sense at all in the end, hence the 'just wondering' part...

**Comment by nholthaus** [comment]
@mlund So I'm going to define some defs/cmake options where you can disable all the predefined units, and then add back only the ones you want. E.g.

```cpp
#define DISABLE_PREDEFINED_UNITS
#define ENABLE_PREDEFINED_LENGTH_UNITS
#define ENABLE_PREDEFINED_TIME_UNITS
// only get length/time, nothing else
```
