### ISSUE TITLE
Why std::ratio?

### ISSUE THREAD

**Issue by MikeGitb** [nholthaus/units#78]
Sorry, if this was already explained somewhere, but why does this library use `std::ratio` instead of simple integers for the unit exponents? Are there usecases, where you need a non-integer exponent?

**Comment by nholthaus** [comment]
I initially wasn't ruling out that there could be fractional unit exponents, at least as temporaries. There are some real fractional units but they're pretty rare. I think I was just being cautious.

What about it don't you like?

**Comment by MikeGitb** [comment]
Mainly curiosity. I implemented my own, simple KMS library just for fun and got curious how "the professionals" do it.

I do wonder however, if it affects compile time.
