### ISSUE TITLE
Unexpected output from units::concentration::percent_t::to<...>()

### ISSUE THREAD

**Issue by GElliott** [nholthaus/units#81]
Consider the following program:

    units::concentration::percent_t x(100.0);
    double y = x.to<double>();
    std::cout << x << std::endl;
    std::cout << y << std::endl;

Output:

    100 pct
    1

I would have expected the scale of the output of `percent_t::to<>()` to match the scale of the constructor parameter.  However, a value of `100` goes in, but a value of `1` comes out.  Is this behavior as intended?

**Comment by MikeGitb** [comment]
100 % equals 1, so this is what I would expect.

**Comment by GElliott** [comment]
I agree that the output should be `1.0`, but shouldn't the constructor instead take `1.0`?  My point is that the scales between constructor parameter and output value seem to be mismatched.

**Comment by nholthaus** [comment]
that's as designed. 1.0/1.0 == 100%.

**Comment by chiphogg** [comment]
It does seem as though this is an inconsistency in the library.  Consider the following test case:

```cpp
TEST(toDouble, consistency) {
    EXPECT_EQ(::units::length::millimeter_t{50}.to<double>(), 50);       // OK
    EXPECT_EQ(::units::length::mile_t{50}.to<double>(), 50);             // OK
    EXPECT_EQ(::units::concentration::percent_t{50}.to<double>(), 0.5);  // surprise!
}
```

Typically in this library, for scaled units, `.to<double>()` is expected to produce the value _in the natively stored unit_.  `percent_t` does not work like that.

I think the operation that's _supposed_ to give `1.0` here would be implicit conversion to `double`.  I believe it already does the right thing here, so the thing to do (_in principle!_) would be to change the _explicit_ `.to<double>()` to be consistent with everything else.

Unfortunately, if this argument is valid, there are probably tremendously many users in the wild which rely on this behaviour, so it's hard for me to see how to fix it.
