### ISSUE TITLE
UNIT_LIB_DISABLE_IOSTREAM causes compile errors

### ISSUE THREAD

**Issue by EvanBalster** [nholthaus/units#87]
Enabling UNIT_LIB_DISABLE_IOSTREAM causes an error while compiling `to_string`, because `<string>` is no longer included.  The lib should either undefine `to_string` or `include <string>` when this macro is enabled.

**Comment by nholthaus** [comment]
Thanks! The testing for the preprocessor definitions is pretty lacking right now 🙁

**Comment by nholthaus** [comment]
of the two solutions you presented, which do you think is better for the embedded case? Undefining `to_string`?

**Comment by EvanBalster** [comment]
Probably undefining to_string.  Or adding another macro to control string enabled/disabled.  Considering that to_string imposes basically the same costs as ostream support, the former makes the most sense to me.

**Comment by yuriy-kozlov** [comment]
I am trying out this units library and I ran into the same issue. I think not defining to_string in this case would make sense. Ideally there would be a separate header to include these features.

My use case is I would like to use units in an API but want to minimize the `#includes` forced on the users of the API.

**Comment by Kaylx** [comment]
I agree with the above suggestions too.  It would be good to enable abbreviation, to_string and ostream separately from each other.
