### ISSUE TITLE
Consider changing the include path for the library

### ISSUE THREAD

**Issue by tarberd** [nholthaus/units#93]
Although using the lib as `#include <units.h>` it's confortable, for a library to be installed on a user's system, it is a better practice to put te lib inside a folder so it would be like `#include <units/units.h>` just like `#include <gtest/gtest.h>`

**Comment by nholthaus** [comment]
have you run into a conflict?

**Comment by tarberd** [comment]
Ney... I've not run into conflict, it's just a mather of consistency. If you look inside the header directorie in linux at `/usr/include` you will be able to see how quickly a mess it can become. I'd reather not contribute to the mess it already is, and keep all package headers inside a folder with the project name. I know it breaks compatibility, hope you consider the change!
Btw, I packaged my fork with this changes already to archlinux and ubuntu.
arch: [tarberd-units-git](https://aur.archlinux.org/packages/tarberd-units-git/)
ubuntu: [units](https://packagecloud.io/tarberd/ophidian)

**Comment by MikeGitb** [comment]
Just one comment regarding collisions (I had one with a non-public library): "units/units.h" is just as generic as "units.h". Would be great, if there was some less generic name/abbreviation that could be used - maybe as simple as `nunits`?

**Comment by tarberd** [comment]
Changing the project name seems to much for me. The name units is already stablished in the code. Changing the name would mess with the namespace. I'd reather have `#include <units/units.h>` matching `using units::foo;` then have the namespace difer from the project name.

**Comment by MikeGitb** [comment]
Has the include path been changed? Or does this mean it will stay as it is? Imho that would be the worst solution.
